### ISSUE TITLE
DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied

### ISSUE THREAD

**Issue by P0tty** [funkandwagnalls/ranger#4]
The target os is win7 just installed.

```
root@kali:~# ranger -u test -p test -t 172.16.236.157 --smbexec -q -v -vv -vvv
[*] Attempting to access the system 172.16.236.157 with, user: test pwd: test domain: WORKGROUP at: 2016-02-29-22:47:25
[*] Trying protocol 445/SMB...
[*] Creating service BTOBTO...
[*] Creating tmp directory
[-] [Errno 17] File exists: '__tmp'
[*] Setting up SMB Server
[*] Config file parsed
[*] Ready to listen...
[-] DCERPC Runtime Error: code: 0x5 - rpc_s_access_denied 
```

**Comment by funkandwagnalls** [comment]
It looks like the problem is with the target not the attack you are using.  The protocol response suggests that either the Administrative Shares are disabled or there is a permission problem with the account.  To help you out I have included instructions below.

**INSTRUCTIONS**
Most domain systems have administrative shares enabled, as mentioned above if this is an unattached system it is unlikely to have Administrative Shares enabled. You can force the shares to be enabled by following the instructions here: [http://www.wintips.org/how-to-enable-admin-shares-windows-7/](url)

Make sure this is a test box you own though since you are creating a vulnerability that may not need to be there.  If you want to determine what shares are exposed and then target them, you can use a tool like `enum4linux` and then use the `--share share_name` argument in ranger to try and execute SMBEXEC.

**WMIC NOTES**
Keep in mind if the system is not attached to a Domain WMIC will not be enabled either, so you will have to troubleshoot enabling that as well.

**VERBOSITY NOTES**
You are also telling ranger to be quiet and then using varying levels of verbosity.  This will not cause the attack to fail, but it will not provide the results in the way you are expecting.  Use one of the following:

`-q, -v, -vv, -vvv`

**Comment by funkandwagnalls** [comment]
You are also telling ranger to be quiet and then using varying levels of verbosity.  This will not cause the attack to fail, but it will not provide the results in the way you are expecting.  Use one of the following:

-q
-v
-vv
-vvv

**Comment by theebrownieee** [comment]
The account could have access to WMIC disabled as well.  Since it's not
a login_failure it indicates the creds are valid.

On Tuesday, March 1, 2016, chrisduffy <notifications@github.com> wrote:

> It looks like the problem is with the target not the attack you are using.
> The protocol response suggests that either the Administrative Shares are
> disabled or there is a permission problem with the account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/funkandwagnalls/ranger/issues/4#issuecomment-190687673>
> .
>


-- 
Sent from my iPhone
